language: csharp
solution: MonoBitter.sln
install:
  - nuget restore MonoBitter.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release /p:DynamicConstants=MONO MonoBitter.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./GitBitterTest/bin/Release/GitBitterTest.dll
